### ISSUE TITLE
How can I switch themes?

### ISSUE THREAD

**Issue by marvin-bitterlich** [brophdawg11/vue-themed-style-loader#3]
@brophdawg11 This tool is great! But it seems that one can only specify one theme at compile time?

I would like to have multiple themes and be able to switch between them dynamically. Is that possible?

**Comment by brophdawg11** [comment]
@reggaemuffin Thanks!  Yes - this tool is mostly for generating separate stylesheets for separate themes, which are then used on separate instances of the site.  It's not really intended for usage of multiple themes in a single site.  In that case, you don't really ever want to skip or replace any themes, so the functionality here or ignoring/replacing `<style>` blocks isn't all that useful.

I think what you are looking for can be accomplished easily without this package.  I would suggest a root theme class that could be toggled appropriately.  Something along the lines of:

```
<template>
    <div :class="activeTheme">
        <h1 class="title">This is the themed title</h1>
        <select v-model="activeTheme">
            <option value="theme-a">Theme A</option>
            <option value="theme-b">Theme B</option>
        </select>       
    </div>
</template>

<script>
export default {
    name: 'App',
    data() {
        return {
            activeTheme: 'theme-a',
        };
    },
};
</script>

<style lang="scss">
// Default color without any theme is black
.title {
    color: black;
}
</style>

<style lang="scss">
// Theme A overrides
.theme-a {
    .title {
        color: red;
    }
}
</style>

<style lang="scss">
// Theme B overrides
.theme-b {
    .title {
        color: blue;
    }
}
</style>
```
